#!/bin/bash

PathDir="$(pwd)"
. $PathDir/dorking.sh
. $PathDir/functionLibrary.sh

#Help function  to display usages
menu_help () {
        echo -e "========================================================================================================================================"
       echo -e "" \                      "\t\t\t\t\t\t  ___             ____  _              ____                      \n" \
                                         "\t\t\t\t\t\t / _ \ _ __   ___/ ___|| |_ ___  _ __ |  _ \ ___  ___ ___  _ __  \n" \
                                         "\t\t\t\t\t\t| | | | '_ \ / _ \___ \| __/ _ \| '_ \| |_) / _ \/ __/ _ \| '_ \ \n" \
                                         "\t\t\t\t\t\t| |_| | | | |  __/___) | || (_) | |_) |  _ <  __/ (_| (_) | | | |\n" \
                                         "\t\t\t\t\t\t \___/|_| |_|\___|____/ \__\___/| .__/|_| \_\___|\___\___/|_| |_|\n" \
                                         "\t\t\t\t\t\t                                |_|                              \n" \
					 ""
        echo -e "========================================================================================================================================"

        echo -e "\n"
        #echo -e "\t-e|--Exploit-DB \t\tVulnerability checker\t\t\t\t\t\t\t[passive]"
        #echo -e "\t-f|--FacebookDataExtractor \tExracts data from facebook  \t\t\t\t\t\t[passive]"
        #echo -e " -dBa | --Dorking \t\t\tRun popular dorking searches using Baidu search engine\t\t\t[Passive]"
        echo -e " -b  | --Banner Grabbing \t\tGain details about a system on a network\t\t\t\t[Semi-Passive]"
	echo -e " -dB | --Dorking \t\t\tRun popular dorking searches using Bing search engine\t\t\t[Passive]"
        echo -e " -dD | --Dorking \t\t\tRun popular dorking searches using Duck Duck Go search engine\t\t[Passive]"
        echo -e " -dG | --Dorking \t\t\tRun popular dorking searches using Google search engine\t\t\t[Passive]"
        #echo -e " -g  | --Banner Grabbing \t\tGain details about a system on a network\t\t\t\t[Passive]"
        echo -e " -M  | --MetaDataExtractor\t\tExracts data from files\t\t\t\t\t\t\t[Passive]"
        echo -e " -m  | --Google Map Request\t\tOpens google map to inputted location\t\t\t\t\t[Passive]"
        echo -e " -n  | --Name Server Enumeration \tLocating all DNS servers and records for a company\t\t\t[Semi-Passive]"
        echo -e " -s  | --Shodan  \t\t\tIoT devices check\t\t\t\t\t\t\t[Passive]"
        echo -e " -t  | --Text file recon \t\tChecks for intel in Robots.txt & Security.txt of domain\t\t\t[Passive]"
        echo -e " -w  | --Whois \t\t\t\tWhois URL check\t\t\t\t\t\t\t\t[Passive]"
}

commandLineSwitch=$1
argumentToPass=$2

if [[ "$commandLineSwitch" == "--help" ]]; then
          menu_help
elif [ "$#" -lt  2  ]; then
        echo "[!] Incorrect nummber of parameter. Use \"--help\" to display help menu."
else
        #if [[ "$commandLineSwitch" == "-dBa" ]]; then
                #Excute_All_Dorkings
        if [[ "$commandLineSwitch" == "-dB" ]]; then
                Excute_All_Dorkings #Bing
        elif [[ "$commandLineSwitch" == "-dD" ]]; then
                Excute_All_Dorkings #Duckduck go
        elif [[ "$commandLineSwitch" == "-dG" ]]; then
                Excute_All_Dorkings # Google
        elif [[ "$commandLineSwitch" == "-n" ]]; then
                dnsCheck "$argumentToPass" #DNS 
        elif [[ "$commandLineSwitch" == "-s" ]]; then
                shodanFunc "$argumentToPass" #Shodan
        elif [[ "$commandLineSwitch" == "-t" ]]; then
                txtFileChecks "$argumentToPass" #robots.txt/security.txt
        elif [[ "$commandLineSwitch" == "-w" ]]; then
                whoIsFunc "$argumentToPass" #whoIs
        elif [[ "$commandLineSwitch" == "-b" ]]; then 
                bannerGrab "$argumentToPass" #banner grabbing
        elif [[ "$commandLineSwitch" == "-m" ]]; then
                googleMaps "$@" #Google Maps
        elif [[ "$commandLineSwitch" == "-M" ]]; then
                metadataExtraction "$@" # Metadata Extraction
        fi
fi
